# Permalinks
permalink:           pretty

# Setup
title:               Dr. James Howe
tagline:             'Cryptography Researcher and Engineer'
description:         'Personal home page'
url:                 https://jameshowe.eu
baseurl:             ''

# About/contact
author:
  name:              James Howe
  email:             jameshoweee@gmail.com

# Plugins (bundled via the github-pages gem)
plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: G-DCEGWP83NC

